version: 0.2

env:
  variables:
    BUCKET_NAME: "test-bucket"

phases:
  pre_build:
    commands:
      - echo "Cleaning up old cache files..."
      - rm -rf node_modules
      - rm -rf package-lock.json  # Ensure fresh install
      - rm -rf test/**/*.d.ts  # Remove unexpected test files
      - |
       echo "BUCKET_NAME from buildspec: ${BUCKET_NAME}"

  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install
      - npm install -g typescript  # Ensure TypeScript is available

  build:
    commands:
      - echo "Running tests and type checks"
      - npm run build --if-present || npx tsc  # Run tsc explicitly if needed
      - npm test || exit 1  # Ensure build fails if tests fail

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Clearing CodeBuild cache..."
      - rm -rf ~/.npm
      - rm -rf /root/.cache