version: 0.2

env:
  variables:
    BUCKET_NAME: "test-bucket"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci  # Ensures exact dependencies from package-lock.json
      - npm install -g typescript  # Ensure TypeScript is globally available
      - npm install --save-dev @types/node @types/jest  # Ensure Node & Jest types
      - npm install --save aws-cdk-lib constructs @aws-sdk/client-s3 @aws-sdk/s3-request-presigner  # Install AWS SDK & CDK dependencies
      
  pre_build:
    commands:
      - echo "Checking IAM identity..."
      - aws sts get-caller-identity
      - echo "Setting up environment variables..."
      - |
       aws s3 ls s3://$BUCKET_NAME || echo "Warning: No access to bucket $BUCKET_NAME"
      - echo "Environment Variables:"
      - printenv
      - |
       echo "BUCKET_NAME from buildspec: ${BUCKET_NAME}"
      - echo "Testing S3 access..."
      - aws s3 ls s3://test-bucket --region us-east-1

  build:
    commands:
      - echo "Running TypeScript type checking..."
      - npx tsc --noEmit  # Ensure all type dependencies exist before building
      - echo "Building project..."
      - npm run build --if-present
      - echo "Running tests..."
      - npm test || exit 1  # Ensure build fails if tests fail

  post_build:
    commands:
      - echo "Build completed"
      - echo "Clearing CodeBuild cache..."
      - rm -rf ~/.npm
      - rm -rf /root/.cache
